apps/mentorados/urls.py
from django.urls import path
from . import views, htmx_views


urlpatterns = [
    path('', views.mentorados, name='mentorados'),
    path('home/', views.home, name='home'),
    path('reunioes/', views.reunioes, name='reunioes'),
    path('autenticar/', views.auth_mentorado, name="auth_mentorado"),
    path('escolher-dia/', views.escolher_dia, name='escolher_dia'),
    path('agendar-reuniao/', views.agendar_reuniao, name='agendar_reuniao'),
    path('<int:id>/tarefa-adicionar/', views.tarefa_adicionar, name='tarefa_adicionar'),
    path('<int:id>/upload/', views.upload, name='upload'),
    path('tarefas/', views.tarefas, name='tarefas'),
]

htmx_urlpatterns = [
    path('add-navigator/', htmx_views.add_navigator, name='add_navigator'),
    path('tarefa-concluir/<int:id_tarefa>/', htmx_views.tarefa_concluir, name='tarefa_concluir'),
    path('busca-horarios/', htmx_views.busca_horarios, name='busca_horarios'),
]

urlpatterns += htmx_urlpatterns

core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, reverse
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('mentorados/', include('mentorados.urls')),
    path('', lambda home: redirect(reverse('home'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/mentorados/models.py
from datetime import timedelta
import secrets
from django.db import models
from django.contrib.auth.models import User

class Navigator(models.Model):
    nome = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE) # mentor

    def __str__(self):
        return self.nome
    
class Mentorado(models.Model):
    estagio_choices = (
        ('E1', '10-100k'),
        ('E2', '100-1KK')
    )
    nome = models.CharField(max_length=255)
    foto = models.ImageField(upload_to='fotos', null=True, blank=True)
    estagio = models.CharField(max_length=2, choices=estagio_choices)
    navigator = models.ForeignKey(Navigator, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, on_delete=models.CASCADE) # mentor
    token = models.CharField(max_length=16, null=True, blank=True)
    criado_em = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.token: 
            self.token = self.gerar_token_unico()
        super().save(*args, **kwargs)

    def gerar_token_unico(self):
        while True:
            token = secrets.token_urlsafe(8)
            if not Mentorado.objects.filter(token=token).exists():
                return token
 
    def __str__(self):
        return self.nome

class DisponibilidadeHorario(models.Model):
    data_inicial = models.DateTimeField(null=True, blank=True)
    mentor = models.ForeignKey(User, on_delete=models.CASCADE)
    agendado = models.BooleanField(default=False)

    @property
    def data_final(self):
        return self.data_inicial + timedelta(minutes=50)
    
class Reuniao(models.Model):
    tag_choices = (
        ('G', 'Gestão'),
        ('M', 'Marketing'),
        ('RH', 'Gestão de pessoas'),
        ('I', 'Impostos')
    )

    data = models.ForeignKey(DisponibilidadeHorario, on_delete=models.CASCADE)
    mentorado = models.ForeignKey(Mentorado, on_delete=models.CASCADE)
    tag = models.CharField(max_length=2, choices=tag_choices)
    descricao = models.TextField()

    class Meta:
        verbose_name_plural = 'reunioes'

class Tarefa(models.Model):
    mentorado = models.ForeignKey(Mentorado, on_delete=models.DO_NOTHING)
    tarefa = models.CharField(max_length=255)
    realizada = models.BooleanField(default=False)

class Upload(models.Model):
    mentorado = models.ForeignKey(Mentorado, on_delete=models.DO_NOTHING)
    video = models.FileField(upload_to='video')

apps/mentorados/views.py
from datetime import datetime, timedelta
import json
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from .auth import valida_token
from mentorados.models import DisponibilidadeHorario, Navigator, Mentorado, Reuniao, Tarefa, Upload
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db import transaction


def home(request):
    c_hide = '' if request.GET.get('src') else 'hidden'
    return render(request, 'home.html', {'c_hide': c_hide})

@login_required
def mentorados(request):
    template_name = 'mentorados.html'
    navigators = Navigator.objects.filter(user=request.user).order_by('nome')
    mentorados = Mentorado.objects.filter(user=request.user).order_by('nome')

    estagios_flat = [i[1] for i in Mentorado.estagio_choices]
    qtd_estagios = []

    for i, j in Mentorado.estagio_choices:
        qtd_estagios.append(Mentorado.objects.filter(estagio=i, user=request.user).count())

    context = {
        'estagios': Mentorado.estagio_choices,
        'navigators': navigators,
        'mentorados': mentorados,
        'estagios_flat': estagios_flat,
        'qtd_estagios': qtd_estagios,
    }
    if request.method == "POST":
        nome = request.POST.get('nome').strip().upper()
        foto = request.FILES.get('foto')
        estagio = request.POST.get("estagio").strip()
        navigator = request.POST.get('navigator').strip()

        context['dados_form'] = request.POST

        if len(nome) == 0 or len(estagio) == 0:
            messages.add_message(request, messages.WARNING, 'Nome e Estágio são obrigatórios !')
            return render(request, template_name, context)

        mentorado = Mentorado(
            nome=nome,
            foto=foto,
            estagio=estagio,
            navigator_id=navigator,
            user=request.user
        )
        try:
            mentorado.save()
            messages.add_message(request, messages.SUCCESS, 'Mentorado cadastrado com sucesso.')
            return redirect(reverse('mentorados'))
        except Exception as e:
            messages.add_message(request, messages.ERROR, f'Erro: {e}')
            return render(request, template_name, context)
    
    return render(request, template_name, context)

@login_required
def reunioes(request):
    template_name = 'reunioes.html'
    data_filter = request.GET.get('data-filter')
    mentorado_filter = request.GET.get('mentorado-filter')

    reunioes = Reuniao.objects.filter(data__mentor=request.user)

    if data_filter:
        data_filter_date = datetime.strptime(data_filter + 'T00:01', '%Y-%m-%dT%H:%M')
        reunioes = reunioes.filter(
            data__data_inicial__gte=data_filter_date,
            data__data_inicial__lte=(data_filter_date + timedelta(minutes=(23*60 + 58)))
        )
    if mentorado_filter:
        reunioes = reunioes.filter(mentorado__nome__icontains=mentorado_filter)

    context = {'reunioes': reunioes, 'data_filter': data_filter, 'mentorado_filter': mentorado_filter}

    if request.method == 'POST':
        data = request.POST.get('data')
        horarios_list = request.POST.getlist('horario')

        disponibilidades = []
        for hora in horarios_list:
            dt = datetime.strptime(data+'T'+hora+':00', '%Y-%m-%dT%H:%M')

            disponibilidade_horario = DisponibilidadeHorario.objects.filter(mentor=request.user, data_inicial=dt)

            if disponibilidade_horario.exists():
                messages.add_message(request, messages.WARNING, f"Você já possui reunião em {dt.strftime('%d/%m/%Y')} às {dt.strftime('%H:%M')}")
                return redirect('reunioes')
            
            disponibilidades.append(DisponibilidadeHorario(data_inicial=dt, mentor=request.user))

        try:
            DisponibilidadeHorario.objects.bulk_create(disponibilidades)
            mensagem = 'Horários disponibilizados' if len(disponibilidades) > 1 else 'Horário disponibilizado'
            messages.add_message(request, messages.SUCCESS, f'{mensagem} com sucesso.')
        except Exception as e:
            messages.add_message(request, messages.ERROR, f'Erro: {e}.')

        return redirect('reunioes')

    return render(request, template_name, context)

def auth_mentorado(request):
    body = json.loads(request.body)
    token = body['token']
    if len(token) == 0:
        return JsonResponse({'status': 2, 'mensagem': 'Token não informado !'})
    
    if not Mentorado.objects.filter(token=token).exists():
        return JsonResponse({'status': 1, 'mensagem': 'Token inválido.'})
    
    return JsonResponse({'status': 0, 'mensagem': 'Sucesso'})

def escolher_dia(request):
    mentorado = valida_token(request.COOKIES.get('auth_token'))
    if not mentorado:
        return redirect('/mentorados/home/?src=escolher-dia')
    
    template_name = 'escolher_dia.html'

    if mentorado:
        disponibilidades = DisponibilidadeHorario.objects.filter(
            data_inicial__gte=datetime.now(),
            agendado=False,
            mentor=mentorado.user
        ).values_list('data_inicial', flat=True)

        datas = sorted(list(set([x.date() for x in disponibilidades])))

        return render(request, template_name, {'datas': datas})
    
    return render(request, template_name)

def agendar_reuniao(request):
    mentorado = valida_token(request.COOKIES.get('auth_token'))
    if not mentorado:
        return redirect('/mentorados/home/?src=escolher-dia')
    
    template_name = 'agendar_reuniao.html'
    data_str = request.GET.get('data')
    data = datetime.strptime(data_str, '%d-%m-%Y')
    horarios = DisponibilidadeHorario.objects.filter(
        data_inicial__gte=data,
        data_inicial__lt=data + timedelta(days=1),
        agendado=False,
        mentor=mentorado.user
    )
    context = {'data': data_str, 'horarios': horarios, 'tags': Reuniao.tag_choices}    

    if request.method == 'POST':
        horario_id = request.POST.get('horario')
        tag = request.POST.get('tag')
        descricao = request.POST.get("descricao")

        if len(horario_id) == 0 or len(tag) == 0 or len(descricao) == 0:
            messages.add_message(request, messages.WARNING, 'Preencha todos os campos !')
            return redirect(f'/mentorados/agendar-reuniao/?data={data_str}')

        try:
            horario = DisponibilidadeHorario.objects.get(id=horario_id)
        except DisponibilidadeHorario.DoesNotExist:
            messages.add_message(request, messages.WARNING, 'Este horário não está cadastrado !')
            return redirect(f'/mentorados/agendar-reuniao/?data={data_str}')

        if horario.mentor != mentorado.user:
            messages.add_message(request, messages.WARNING, 'Este horário não pertence ao seu mentor !')
            return redirect(f'/mentorados/agendar-reuniao/?data={data_str}')

        reuniao = Reuniao(
            data_id=horario_id,
            mentorado=mentorado,
            tag=tag,
            descricao=descricao
        )

        try:
            with transaction.atomic():
                reuniao.save()
                # horario = horario
                # horario.agendado = True
                # horario.save()
                reuniao.data.agendado = True
                reuniao.data.save()

            messages.add_message(request, messages.SUCCESS, 'Reunião agendada com sucesso.')
            return redirect(reverse('escolher_dia'))
        except Exception as e:
            messages.add_message(request, messages.ERROR, f'Erro: {e}.')
            return redirect(f'/mentorados/agendar-reuniao/?data={data_str}')

    return render(request, template_name, context)

@login_required
def tarefa_adicionar(request, id): #id do mentorado
    mentorado = Mentorado.objects.get(id=id)
    if mentorado.user != request.user:
        raise Http404()
    template_name = 'tarefa_adicionar.html'
    tarefas = Tarefa.objects.filter(mentorado=mentorado)
    videos = Upload.objects.filter(mentorado=mentorado)
    context = {'mentorado': mentorado, 'tarefas': tarefas, 'videos': videos}

    if request.method == 'POST':
        tarefa_descricao = request.POST.get('tarefa').strip()

        if len(tarefa_descricao) == 0:
            messages.add_message(request, messages.WARNING, 'Tarefa não informada !')
            return redirect(f'/mentorados/{mentorado.id}/tarefa-adicionar/')

        tarefa = Tarefa(
            mentorado=mentorado,
            tarefa=tarefa_descricao,
        )
        try:
            tarefa.save()
            messages.add_message(request, messages.SUCCESS, 'Tarefa adicionada com sucesso.')
        except Exception as e:
            messages.add_message(request, messages.ERROR, f'Erro: {e}.')
            
        return redirect(f'/mentorados/{mentorado.id}/tarefa-adicionar/')
    
    return render(request, template_name, context)

@login_required
def upload(request, id): #id do mentorado
    if request.method == 'POST':
        mentorado = Mentorado.objects.get(id=id)
        if mentorado.user != request.user:
            raise Http404()
        
        video = request.FILES.get('video')

        if not video:
            messages.add_message(request, messages.WARNING, 'Vídeo não escolhido !')
            return redirect(f'/mentorados/{mentorado.id}/tarefa-adicionar/')

        upload = Upload(mentorado=mentorado, video=video)

        try:
            upload.save()
            messages.add_message(request, messages.SUCCESS, 'Vídeo enviado com sucesso.')
        except Exception as e:
            messages.add_message(request, messages.ERROR, f'Erro: {e}.')
        
        return redirect(f'/mentorados/{mentorado.id}/tarefa-adicionar/')

def tarefas(request):
    mentorado = valida_token(request.COOKIES.get('auth_token'))
    if not mentorado:
        return redirect('/mentorados/home/?src=tarefas')
    

apps/mentorados/templates/mentorados.html
{% extends "base.html" %}
{% load static %}

{% block 'title' %}Mentorados{% endblock 'title' %}

{% block 'body' %}
<div class="bg-[#040e1b] min-h-screen">
    <div class="max-w-7xl mx-auto p-12">
        <div class="grid grid-cols-2 gap-4">
            <div>
                <h2 class="my-4 text-2xl/9 font-bold tracking-tight text-gray-100">Cadastre seus mentorados</h2> 
                {% include "partials/messages.html" %}
                <form class="mt-6" action="{% url 'mentorados' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-4">
                        <label class="block text-sm/6 font-medium text-gray-200">Nome</label>
                        <input type="text" name="nome" value="{{dados_form.nome}}" class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6" required autofocus>
                    </div>
                    <div class="grid grid-cols-3 gap-4">
                        <div class="col-span-2 mb-4">
                            <label class="block text-sm/6 font-medium text-gray-200">Foto</label>
                            <input type="file" name="foto" autocomplete="foto" class="block w-full rounded-md bg-white/5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6 file:bg-indigo-600 file:py-1.5 file:px-2 hover:file:bg-indigo-500 file:cursor-pointer cursor-pointer">
                        </div>
                        <div class="mb-4">
                            <label class="block text-sm/6 font-medium text-gray-200">Estágio</label>
                            <select name="estagio" class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6 min-h-9">
                                <option class="text-slate-900" value="">- - -</option>
                                {% for estagio in estagios  %}
                                    <option class="text-slate-900" value="{{estagio.0}}"
                                        {% if estagio.0 == dados_form.estagio %}
                                            selected
                                        {% endif %}
                                    >{{estagio.1}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="flex items-end gap-4 mb-4">
                        <div class="flex-1">
                            <label class="block text-sm/6 font-medium text-gray-200">Navigator</label>
                            <select name="navigator" id="navigator" class="block w-full rounded-md bg-white/5 px-3 py-2 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                                {% include "options_navigator.html" %}
                            </select>
                        </div>
                        <button id="open_modal" class="flex-none text-white cursor-pointer rounded-md bg-indigo-600 p-[5px] text-sm/6 font-semibold shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                            </svg>
                        </button>
                    </div>
                    <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mt-6">Cadastrar</button>
                </form>
            </div>
            <div class="flex justify-center items-center w-1/2 mx-auto">
                <canvas id="myChart" class="w-24 h-24"></canvas>
            </div>
        </div>
        <div class="mt-6">
            <hr class="border-gray-600">
            <br>    
            <h2 class="text-xl font-semibold text-white">Seus mentorados</h2>
            <table class="mt-6 w-full whitespace-nowrap text-left">
                <colgroup>
                    <col class="w-full sm:w-4/12">
                    <col class="lg:w-4/12">
                    <col class="lg:w-2/12">
                    <col class="lg:w-1/12">
                    <col class="lg:w-1/12">
                </colgroup>
                <thead class="border-b border-white/10 text-sm/6 text-white">
                    <tr>
                        <th scope="col" class="py-2 pl-4 pr-8 font-semibold sm:pl-6 lg:pl-8">Nome</th>
                        <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold sm:table-cell">Estágio</th>
                        <th scope="col" class="py-2 pl-0 pr-4 text-right font-semibold sm:pr-8 sm:text-left lg:pr-20">Status</th>
                        <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Data entrada</th>
                        <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Navigator</th>
                        <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Tarefas</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-white/5">
                    {% for mentorado in mentorados %}
                        <tr>
                            <td class="py-4 pl-4 pr-8 sm:pl-6 lg:pl-8">
                                <div class="flex items-center gap-x-4">
                                    <img src="{% if mentorado.foto %}{{mentorado.foto.url}}{% endif %}" alt="" class="size-8 rounded-full bg-gray-800">
                                    <div class="truncate text-sm/6 font-medium text-white">{{mentorado.nome}}</div>
                                </div>
                            </td>
                            <td class="hidden py-4 pl-0 pr-4 sm:table-cell sm:pr-8">
                                <div class="flex gap-x-3">
                                    <div class="rounded-md bg-gray-700/40 px-2 py-1 text-xs font-medium text-gray-400 ring-1 ring-inset ring-white/10">{{mentorado.get_estagio_display}}</div>
                                </div>
                            </td>
                            <td class="py-4 pl-0 pr-4 text-sm/6 sm:pr-8 lg:pr-20">
                                <div class="flex items-center justify-end gap-x-2 sm:justify-start">
                                    <div class="flex-none rounded-full bg-green-400/10 p-1 text-green-400">
                                        <div class="size-1.5 rounded-full bg-current"></div>
                                    </div>
                                    <div class="hidden text-white sm:block">Ativo</div>
                                </div>
                            </td>
                            <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">
                                {{mentorado.criado_em|date:'d/m/Y'}}
                            </td>
                            <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">
                                {{mentorado.navigator.nome}}
                            </td>
                            <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">
                                <a href="{% url 'tarefa_adicionar' mentorado.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- modal cadastrar navigator -->
    {% include "modal_navigator.html" %}

</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/htmx.min.js' %}"></script>
<script src="{% static 'mentorados/js/navigator.js' %}"></script>

<script>
    const ctx = document.getElementById('myChart');

    new Chart(ctx, {
        type: 'pie',
        data: {
        labels: {{estagios_flat|safe}},
        datasets: [{
            label: '',
            data: {{qtd_estagios|safe}},
            borderWidth: 1
        }]
        },
        
    });

</script>

{% endblock 'body' %}

apps/mentorados/templates/options_navigator.html
<option class="text-slate-900" value="">- - -</option>      
{% for navigator in navigators  %}
    <option class="text-slate-900" value="{{navigator.id}}">
        {{navigator.nome}}
    </option>  
{% endfor %}

apps/mentorados/templates/tarefas.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}Tarefa mentorado{% endblock 'title' %}

{% block 'body' %}
<main>
    <header class="relative isolate pt-3 bg-[#0b1526] border-b-1 border-slate-500">
        <a href="{% url 'home' %}" class="block size-25 mx-auto mb-3"><img src="{% static 'img/logo.png' %}" alt="Logo do site"></a>
        <div class="absolute inset-0 -z-10 overflow-hidden" aria-hidden="true">
            <div class="absolute left-16 top-full -mt-16 transform-gpu opacity-50 blur-3xl xl:left-1/2 xl:-ml-80">
                <div class="aspect-[1154/678] w-[72.125rem] bg-gradient-to-br from-[#FF80B5] to-[#9089FC]" style="clip-path: polygon(100% 38.5%, 82.6% 100%, 60.2% 37.7%, 52.4% 32.1%, 47.5% 41.8%, 45.2% 65.6%, 27.5% 23.4%, 0.1% 35.3%, 17.9% 0%, 27.7% 23.4%, 76.2% 2.5%, 74.2% 56%, 100% 38.5%)"></div>
            </div>
            <div class="absolute inset-x-0 bottom-0 h-px bg-gray-900/5"></div>
        </div>
        <div>
            <div class="mx-auto max-w-7xl p-2 sm:px-6 lg:px-8 ">
                <div class="mx-auto flex max-w-2xl items-center justify-between gap-x-8 lg:mx-0 lg:max-w-none">
                    <div class="flex items-center gap-x-6">
                        <img src="{% if mentorado.foto %}{{mentorado.foto.url}}{% endif %}" alt="Foto do mentorado" class="size-16 flex-none rounded-full ring-1 ring-gray-900/10">
                        <h1>
                            <div class="mt-1 text-base font-semibold text-gray-200">{{mentorado}}</div>
                            <div class="text-sm/6 text-gray-500">{{mentorado.get_estagio_display}}</div>
                        </h1>
                    </div>

                </div>

            </div>
        </div>
    </header>

    <div class="bg-[#05101d] min-h-screen">
        <div class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
            <div class="mx-auto flex max-w-2xl gap-8 sm:flex-col lg:mx-0 lg:max-w-none lg:flex-row-reverse">
                <!-- Invoice summary -->
                <div class="lg:basis-[40vw]">
                    <div class="rounded-lg shadow-sm ring-1 ring-white/20 bg-[#0b1526]">
                        <div class="flex flex-wrap">
                            <div class="flex-auto px-6 pt-6">
                                <h2 class="text-2xl/9 font-semibold tracking-tight text-gray-100 mb-2">Reuniões</h2>
                            </div>
                            
                            {% for video in videos %}
                                <div class="flex w-full flex-none gap-x-4 border-t border-gray-50/10 px-6 py-6">
                                    <dt class="flex-none">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-6 w-5 text-gray-400">
                                        <path d="M4.5 4.5a3 3 0 0 0-3 3v9a3 3 0 0 0 3 3h8.25a3 3 0 0 0 3-3v-9a3 3 0 0 0-3-3H4.5ZM19.94 18.75l-2.69-2.69V7.94l2.69-2.69c.944-.945 2.56-.276 2.56 1.06v11.38c0 1.336-1.616 2.005-2.56 1.06Z" />
                                        </svg>
                                        
                                        
                                    </dt>
                                    <dd class="text-sm/6 font-medium text-blue-400"><a href="{{video.video.url}}" target="_blank">{{video.mentorado}}</a></dd><p class="text-sm/6 text-white">10 - 5</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <!-- Invoice -->
                <div class="lg:basis-[60vw]">
                    <div class="rounded-lg shadow-sm ring-1 ring-white/20 bg-[#0b1526]">
                        <div class="flex flex-wrap">
                            <div class="flex-auto px-6 pt-6">
                                <h2 class="text-2xl/9 font-bold tracking-tight text-gray-100 mb-2">Tarefas do mentorado</h2>
                            </div>
                            <hr class="border-px border-slate-800">
                            <div class="flex flex-col border-t border-gray-50/10 w-full p-6">
                                {% for tarefa in tarefas %} 
                                <div class="flex items-center mb-4">
                                    <input id="default-checkbox" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600" hx-post="/mentorados/tarefa-concluir/{{tarefa.id}}/" hx-trigger="click" hx-confirm="Confirma a alteração ?"
                                    {% if tarefa.realizada %} checked {% endif %}>
                                    <label for="default-checkbox" class="ms-2 text-sm font-medium text-gray-300 dark:text-gray-300">{{tarefa.tarefa}}</label>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
        {% csrf_token %}
    </div>

    </main>
    <script src="{% static 'js/htmx.min.js' %}"></script>
{% endblock 'body' %}